<script src="{{ url('vendors/popper/popper.min.js') }}"></script>
    <script src="{{ url('vendors/bootstrap/bootstrap.min.js') }}"></script>
    <script src="{{ url('vendors/anchorjs/anchor.min.js') }}"></script>
    <script src="{{ url('vendors/is/is.min.js') }}"></script>
    <script src="{{ url('vendors/fontawesome/all.min.js') }}"></script>
    <script src="{{ url('vendors/lodash/lodash.min.js') }}"></script>
    <script src="{{ url('vendors/list.js/list.min.js') }}"></script>
    <script src="{{ url('vendors/feather-icons/feather.min.js') }}"></script>
    <script src="{{ url('vendors/dayjs/dayjs.min.js') }}"></script>
    <script src="{{ url('assets/js/phoenix.js') }}"></script>
    <script src="{{ url('vendors/leaflet/leaflet.js') }}"></script>
    <script src="{{ url('vendors/leaflet.markercluster/leaflet.markercluster.js') }}"></script>
    <script src="{{ url('vendors/leaflet.tilelayer.colorfilter/leaflet-tilelayer-colorfilter.min.js') }}"></script>
    <script src="{{ url('assets/js/phoenix.js') }}"></script>
    <script src="{{ url('vendors/echarts/echarts.min.js') }}"></script>
    <script src="{{ url('assets/js/ecommerce-dashboard.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
